name: Daily Build

on:
  schedule:
    - cron: '0 0 * * *' # 00:00 UTC nightly
  workflow_dispatch: # Manual trigger

jobs:
  debian-build:
    strategy:
      matrix:
        host: [ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.host }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          DATE=$(date -u +"%Y%m%d")
          VERSION="0.1-$DATE"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "HOST=${{ matrix.host }}" >> $GITHUB_ENV
          echo "Version set to $VERSION for host ${{ matrix.host }}"

      - name: Install build/packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts debhelper build-essential fakeroot \
            meson ninja-build zip xz-utils zstd lzma lzip

      - name: Update control.daily
        run: |
          cp debian/control debian/control.daily
          echo "# Daily build version: $VERSION" >> debian/control.daily

      - name: Build Debian package
        run: |
          # Bump changelog with new version (don't recreate)
          dch --newversion "${VERSION}" "Automated daily build"
          dpkg-buildpackage -us -uc -b

      - name: Build with Meson/Ninja
        run: |
          meson setup build --buildtype=release
          meson compile -C build

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          BIN_DIR=build
          PREFIX=kuznix-tui-de-${VERSION}-${HOST}

          # Tarballs
          tar -czf artifacts/${PREFIX}-bin.tar.gz -C $BIN_DIR .
          tar -cJf artifacts/${PREFIX}-bin.tar.xz -C $BIN_DIR .
          tar --zstd -cf artifacts/${PREFIX}-bin.tar.zst -C $BIN_DIR .
          tar --lzip -cf artifacts/${PREFIX}-bin.tar.lz -C $BIN_DIR .

          # Debian package (rename with host)
          mv ../*.deb artifacts/${PREFIX}.deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kuznix-tui-de-${{ env.VERSION }}-${{ matrix.host }}
          path: artifacts/*

      - name: Commit and push updated control.daily
        if: matrix.host == 'ubuntu-latest' # run only once
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add debian/control.daily
          git commit -m "Update debian/control.daily for version $VERSION" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
