name: Daily Build

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch:     # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        host: [ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts build-essential debhelper lintian \
            fakeroot dh-make tar xz-utils zstd lzip

      - name: Set env vars
        run: |
          VERSION="0.1+kuznix-daily-$(date -u +%Y%m%d)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "HOST=${{ matrix.host }}" >> $GITHUB_ENV

      - name: Bump changelog with new version
        run: |
          dch --newversion "${VERSION}" --force-bad-version "Automated daily build"
          dpkg-buildpackage -us -uc -b
        env:
          DEBEMAIL: "krzysztofdemirkuzniak@gmail.com"
          DEBFULLNAME: "Krzysztof Demir Kuźniak"

      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          cp ../*.deb artifacts/ || true
          cp ../*.dsc artifacts/ || true
          cp ../*.tar.* artifacts/ || true
          # Convert source tarballs to extra formats
          for src in ../*.tar.*; do
            [ -f "$src" ] || continue
            base=$(basename "$src" | sed "s/\.tar\..*//")
            cp "$src" "artifacts/${base}.tar.gz"
            cp "$src" "artifacts/${base}.tar.xz"
            zstd -q -f -o "artifacts/${base}.tar.zst" "$src"
            lzip -q -f -o "artifacts/${base}.tar.lz" "$src"
          done

          # Rename layout: {reponame}-{version}-{host}
          for f in artifacts/*; do
            base=$(basename "$f")
            mv "$f" "artifacts/kuznix-tui-de-${VERSION}-${HOST}-${base}"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kuznix-tui-de-${{ env.VERSION }}-${{ env.HOST }}
          path: artifacts/*
